theme = ["github.com/dzello/reveal-hugo"]

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.tableOfContents]
  startLevel = 1
  endLevel = 4

[minify]
  disableHTML = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
